apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/deopura/sample-app.git
    targetRevision: main
    path: manifests/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app
  syncPolicy:
    automated:
      prune: true       # deletes resources removed from Git
      selfHeal: true     # reverts manual kubectl edits back to Git state
    syncOptions:
      - CreateNamespace=true
